---
# Implement your workload removal tasks here
# ------------------------------------------


# This playbook is called upon deletion of the environment
# OpenShift resources get deleted automatically
# Need to cleanup after ourselves in RHV though.

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: Role kafka | Task remove_workload | Remove_workload tasks complete
  ansible.builtin.debug:
    msg: "Remove Workload tasks completed successfully."
  when: not kafka_silent | bool